### ISSUE TITLE
存在连接不稳定的问题

### ISSUE THREAD

**Issue by sv3nbeast** [akkuman/rotateproxy#1]
![image](https://user-images.githubusercontent.com/55974091/142798501-b737f1d3-4094-408a-b68f-b69942aa7dbb.png)

./rotateproxy -email "xxxx@xx.com" -token 6453d19 -region 1 -page 1
使用的这个命令
在连接socks5代理的时候，存在不少连接失败的的问题，会导致没办法正常使用，是不是验证存活的时候需要使用更加完善的方法呢
* 感谢您分享的此工具

**Comment by s0k** [comment]
> ![图片](https://user-images.githubusercontent.com/55974091/142798501-b737f1d3-4094-408a-b68f-b69942aa7dbb.png)
> 
> ./rotateproxy -email " [xxxx@xx.com](mailto:xxxx@xx.com) " -token 6453d19 -region 1 -page 1 使用的这个命令 在连接socks5代理的时候，存在连接失败的问题，会导致没办法正常使用，是不是验证成长的时候需要使用更加完善的方法呢
> 
> * 谢谢你分享的这个工具

这个貌似是优化版本，https://github.com/Liang2580/rotateproxy/tree/2.0

**Comment by akkuman** [comment]
新版本应该极大改善了这个问题，可以尝试一下，如果有需要，可以重新打开这个issue

**Comment by safebaseline** [comment]
可用性检测还是要继续优化

**Comment by safebaseline** [comment]
期待优化得更好
