### ISSUE TITLE
mac使用报错

### ISSUE THREAD

**Issue by savior-only** [akkuman/rotateproxy#10]
可以正常抓取代理，curl --socks5 127.0.0.1:5555 cip.cc使用代理时报错

[*] use 43.240.75.131
[!] transport error: [!] copyBuffer: runtime error: invalid memory address or nil pointer dereference
[*] close connection: runtime error: invalid memory address or nil pointer dereference

**Comment by kingz40o** [comment]
+1

**Comment by akkuman** [comment]
@savior-only @kingz40o 一直是错误吗？因为我这边没有mac环境，所以没法测

**Comment by savior-only** [comment]
> @savior-only @kingz40o 刚开始可以用，，过了几天就不行了，，可以正常抓代理，，走代理就报错，，我朋友也是一样

**Comment by DevilMayCrying** [comment]
删除同目录下db文件后即可使用，怀疑是历史数据无法使用导致

**Comment by akkuman** [comment]
@DevilMayCrying 好的，谢谢反馈，这两天修复一下
