### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by ymbzd** [akkuman/rotateproxy#16]
![image](https://user-images.githubusercontent.com/39881690/221138117-e9ff38d5-73ba-4542-bc8b-2f97524865cd.png)
fofa好像改版了，爬不到东西

**Comment by akkuman** [comment]
因为 https://github.com/akkuman/rotateproxy/pull/14 添加了默认的检查 url 为 google，该默认改为空
该问题应该已经修复
https://github.com/akkuman/rotateproxy/releases/tag/v0.8.0
