### ISSUE TITLE
通过浏览器可以走代理访问，但是通过curl 却无法走代理访问成功

### ISSUE THREAD

**Issue by bilisheep** [akkuman/rotateproxy#25]
<img width="566" alt="image" src="https://github.com/akkuman/rotateproxy/assets/69887465/d11ac864-0626-4ab1-b77c-679a8885e076">

**Comment by akkuman** [comment]
浏览器会给每个站点保留一些tcp长连接，如果无法连接会尝试重试，而curl每次调用都是一个新的tcp连接，该工具会给每个tcp连接创建时自动选择一个socks5代理，所以可能会选择到不可用的代理，另外你的第二个图上是已经访问成功了
