### ISSUE TITLE
这是什么原因

### ISSUE THREAD

**Issue by safebaseline** [akkuman/rotateproxy#5]
![image](https://user-images.githubusercontent.com/38883009/147843966-03b068bb-a6e9-4d0a-a17b-6f6d82729f52.png)

**Comment by safebaseline** [comment]
*] close connection: runtime error: invalid memory address or nil pointer dereference
ocks handshake with downstream failed: connection is nil

**Comment by akkuman** [comment]
一般是某一端的链路断开了

**Comment by safebaseline** [comment]
已收到
