### ISSUE TITLE
给菜鸡们写条完整的配置吧

### ISSUE THREAD

**Issue by taotaoli123** [akkuman/rotateproxy#8]
参数有点抽象 一脑子浆糊 麻烦大大给写个完整的配置吧

**Comment by izj007** [comment]
> 参数有点抽象 一脑子浆糊 麻烦大大给写个完整的配置吧

我帮大大答一下
简单使用  ./rotateproxy -email fofaemail -token fofaapitoken
就可以使用工具连接本机的8899端口当做s5代理使用了

**Comment by akkuman** [comment]
@taotaoli123 
可以参见@izj007 提供的命令
如果需要给本机的代理端口加上账号密码认证，可以增加 `-user username -pass password` 参数
